male(alex).
wife(alex,lina).
female(lina).
husband(lina,alex).
female(julia).
mother(julia,lina).
father(julia,alex).
sibling(julia,rosa).
female(rosa).
mother(rosa,lina).
father(rosa,alex).
sibling(rosa,julia).
male(romeo).
wife(romeo,julia).
female(silvia).
mother(silvia,rosa).
male(otto).
mother(otto,silvia).
wife(otto,irma).
male(pascal).
mother(pascal,silvia).
sibling(pascal,otto).
male(jean).
mother(jean,irma).
father(jean,otto).
wife(jean,marie).
sibling(jean,olga).
female(marie).
husband(marie,jean).
female(tina).
father(tina,jean).
mother(tina,marie).
male(peter).
wife(peter,ruth).
father(peter,romeo).
mother(peter,julia).
female(ruth).
husband(ruth,peter).
female(irma).
mother(irma,ruth).
father(irma,peter).
husband(irma,otto).
sibling(irma,georg).
female(olga).
mother(olga,irma).
father(olga,otto).
sibling(olga,jean).
male(georg).
father(georg,peter).
mother(georg,ruth).
sibling(georg,irma).
male(bruno).
mother(bruno,eva).
father(bruno,peter).
sibling(bruno,georg).
female(eva).
husband(eva,oscar).
female(ida).
mother(ida,eva).
father(ida,oscar).
sibling(ida,bruno).
male(oscar).
wife(oscar,eva).
